### ISSUE TITLE
Inconsistent behaviour when opening new files

### ISSUE THREAD

**Issue by behzade** [samjwill/nvim-unception#77] opened 2023-04-11 12:54 UTC
Hi. Thanks for the great plugin!
Recently I've ran into a problem when opening new files in terminal might cause a nested neovim session to be created. The behavior is inconsistent and sometimes it works as intended and sometimes creates a nested session.

I managed to fix the problem by commenting out
`
    vim.fn.chanclose(sock)
` 
in client.lua. Would appreciate it if you could look into this problem.

kitty terminal, neovim version v0.9.0

**Comment by samjwill** [comment] 2023-04-11 14:25
Hi! Thanks for the bug report. I'm thinking that this might be caused by my use of `rpcnotify` instead of `rpcrequest` [here](https://github.com/samjwill/nvim-unception/blob/e8f068dc94112cca368ab7363583b24678fdf510/lua/client/client.lua#L27). The former is asynchronous, so closing the socket directly afterwards may be a race condition?

I'll go ahead and update that. In the meantime, would you be able to verify that changing `rpcnotify` to `rpcrequest` on that line fixes your problem? I've made a branch with the change here if you'd like to pull it: https://github.com/samjwill/nvim-unception/tree/samjwill-patch-1

**Comment by behzade** [comment] 2023-04-11 16:16
The change does indeed fix the problem.

**Closed** 2023-04-11 16:18 UTC
