### ISSUE TITLE
Unception failing on MacOS with zsh and iTerm

### ISSUE THREAD

**Issue by Tolomeo** [samjwill/nvim-unception#21] opened 2022-10-20 22:42 UTC
Hi there,
thanks for the plugin. I like the simplicity and effectiveness of the implementation.

It seems not to be working though, as the remote command sent to the server fails to execute and the command itself leaks into the shell.
After some exploratory debugging I found that it works when I escape also the initial keys `<C-\\><C-N>` as `\\<C-\\>\\<C-N>`

I am using NVIM v0.8.0, on macOS 12.6 (iTerm 3.4.16).

**Comment by samjwill** [comment] 2022-10-20 22:57
Thanks for the error report!

Hmm... that is interesting. Perhaps it's a difference between how bash and zsh (which I presume is the shell you're using since it's a Mac) handle escaping the `<` character? Not 100% sure how to solve this without breaking it for bash on Linux, but I'll look into it!

**Comment by Tolomeo** [comment] 2022-10-20 23:13
That's right, I am on zsh.
It could also be related to how vim interprets string commands: in certain cases it is needed to define keystrokes with escape sequences (https://learnvimscriptthehardway.stevelosh.com/chapters/30.html or https://learnvimscriptthehardway.stevelosh.com/chapters/31.html).
But if I was right I wouldn't know how to explain why it works with bash and not with zsh

**Comment by Tolomeo** [comment] 2022-10-20 23:17
I will try with a different terminal and let you know

**Comment by samjwill** [comment] 2022-10-21 01:28
I wonder if I can't just insert the digraphs for `ctrl-\ ctrl-n` directly into the lua script. I made a new branch with some and it seems to work for me.

Would you want to checkout the branch I made called [macos_bug](https://github.com/samjwill/nvim-unception/tree/macos_bug) and see if that works on the terminal emulator exhibiting the initial bug?

You can do it with packer with something along the lines of:
```
use
{
    "samjwill/nvim-unception",
    branch="macos_bug"
}
```

**Comment by Tolomeo** [comment] 2022-10-21 10:15
I tried installing from the macos_bug, and unfortunately it doesn't fix the issue.
The resulting behaviour is just returning to the terminal emulator with no output.

**Comment by Tolomeo** [comment] 2022-10-21 14:59
I know about this one https://github.com/sickcodes/Docker-OSX 
Maybe it helps?

**Comment by samjwill** [comment] 2022-10-21 16:39
Hi again!

I was able to reproduce the issue. It appears to be caused by the `realpath` command not being installed by default on MacOS.

Installing it via `brew install coreutils` and ensuring it's available in your `$PATH` appears to have fixed the issue. Could you verify that this remedies your problem?

**Comment by Tolomeo** [comment] 2022-10-21 19:00
Hey there, yes I needed to install coreutils using homebrew indeed, but that didn't solve the issue for me. Not until escaping the keycodes at least.
Have you managed to have it working in a macos-like environment with coreutils installed and without escaping?

**Comment by samjwill** [comment] 2022-10-21 19:15
My friend let me use his MacBook, which I believe is a machine running Monterey, and yes, with default terminal emulator and the main branch of the plugin installed, it did appear to function properly after installing coreutils, which is why I figured missing coreutils was the issue.

Issues that are hard to reproduce are the worst 😂😭.

**Comment by Tolomeo** [comment] 2022-10-21 20:50
That's true, the plugins is working with Terminal.app so the issue resides in my configuration of iTerm.
Will let you know if I find out what causes it.

**Comment by Tolomeo** [comment] 2022-10-21 20:52
Thanks for the help!

**Comment by samjwill** [comment] 2022-10-21 21:13
You're welcome!

Something that just occurred to me, and I have no idea if this would actually cause the issue or not, is if your PS1 isn't properly escaped or has some unexpected characters in it. Perhaps try setting that to a simple "`$`" temporarily and see if that does the trick!

I wish you luck in finding the solution; let me know if there's anything I can do on my end. I'm going to close the issue for now, but feel free to re-open it if you think of anything that I can do to prevent this behavior, or find that it's not a quirk with the iTerm configuration.

**Closed by samjwill** 2022-10-21 21:13 UTC
